spring:
  application:
    name: docfy-backend

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/docfy}
    username: ${DB_USER:docfy}
    password: ${DB_PASSWORD:docfy_local}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      show-details: never