spring:
  application:
    name: docfy-backend

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true

  servlet:
    multipart:
      max-file-size: ${DOCFY_FILE_REQUEST_MAX_SIZE:11MB}
      max-request-size: ${DOCFY_FILE_REQUEST_MAX_SIZE:11MB}

management:
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      show-details: never

docfy:
  files:
    storage-location: ${DOCFY_FILE_STORAGE_PATH:./data/files}
    max-size: ${DOCFY_FILE_MAX_SIZE:10MB}

  security:
    jwt:
      secret: ${JWT_SECRET}
      issuer: ${JWT_ISSUER:docfy}
      expiration-seconds: ${JWT_EXPIRATION_SECONDS:3600}
